"""empty message

Revision ID: 7e90ab6a731b
Revises: 
Create Date: 2023-07-10 20:15:02.923968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e90ab6a731b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divar_users',
    sa.Column('PhoneNumber', sa.String(length=11), nullable=False),
    sa.Column('NationalCode', sa.String(length=11), nullable=True),
    sa.Column('AccountVerified', sa.Boolean(), nullable=False),
    sa.Column('IdentityVerified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Updated_at', sa.BIGINT(), nullable=False),
    sa.Column('Created_at', sa.DateTime(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('NationalCode'),
    sa.UniqueConstraint('PhoneNumber'),
    sa.UniqueConstraint('PublicKey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divar_users')
    # ### end Alembic commands ###
