"""empty message

Revision ID: eb54f159f3a4
Revises: 950d040b9795
Create Date: 2023-05-28 14:09:40.322896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb54f159f3a4'
down_revision = '950d040b9795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divar_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PhoneNumber', sa.String(length=11), nullable=False))
        batch_op.create_unique_constraint(None, ['PhoneNumber'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divar_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('PhoneNumber')

    # ### end Alembic commands ###
